(function () {
    const { state, subscribe, syncRoute, navigate, navigateTab } = window.App.Store;
    const app = document.getElementById('app');
    let isBooting = true;
    const views = () => ({ landing: window.App.Views.Landing, patientDashboard: window.App.Views.PatientDashboard, patient: window.App.Views.Patient, doctor: window.App.Views.Doctor, queue: window.App.Views.Queue, staff: window.App.Views.Staff, login: window.App.Views.Login, analytics: window.App.Views.Analytics, patientDonations: window.App.Views.PatientDonations, patientHistory: window.App.Views.PatientHistory, doctorDonations: window.App.Views.DoctorDonations, donations: window.App.Views.Donation, about: window.App.Views.Info, terms: window.App.Views.Info, privacy: window.App.Views.Info, notFound: window.App.Views.NotFound });
    function renderSplash() { app.innerHTML = `<main class="splash-screen" aria-label="Loading SmartCare"><div class="splash-inner"><div class="splash-mark"><i data-lucide="heart-pulse" width="34" height="34"></i></div><h1>SmartCare</h1><p>Care access, clearly organized.</p><div class="splash-progress" aria-hidden="true"></div></div></main>`; if (window.lucide) window.lucide.createIcons(); }
    function renderConnectionStatus() { document.querySelector('.connection-banner')?.remove(); if (navigator.onLine) return; const banner = document.createElement('div'); banner.className = 'connection-banner'; banner.setAttribute('role', 'status'); banner.setAttribute('aria-live', 'polite'); banner.innerHTML = '<i data-lucide="wifi-off" width="16" height="16"></i><span><strong>You are offline.</strong> Saved browser data remains available, but maps and remote updates may not refresh.</span>'; document.body.appendChild(banner); if (window.lucide) window.lucide.createIcons(); }
    function resetScroll() { window.scrollTo({ top: 0, left: 0, behavior: 'instant' }); const workspaceContent = document.querySelector('.workspace-content'); if (workspaceContent) workspaceContent.scrollTop = 0; }
    function scrollToHash() { const hash = window.location.hash.slice(1); if (!hash) return; const target = document.getElementById(decodeURIComponent(hash)); if (target) window.requestAnimationFrame(() => target.scrollIntoView({ behavior: 'smooth', block: 'start' })); }
    function renderFailure() { app.innerHTML = `<main class="app-error section-error" data-section="render-error" aria-labelledby="render-error-title"><div class="app-error-mark"><i data-lucide="triangle-alert" width="30" height="30"></i></div><p class="eyebrow eyebrow-dark"><span class="eyebrow-dot"></span> SmartCare</p><h1 id="render-error-title">This screen needs a refresh.</h1><p>Something interrupted this page. Your saved demo details are still protected on this device.</p><button id="render-error-home" class="btn-primary btn-icon" type="button">Return home <i data-lucide="arrow-right" width="16" height="16"></i></button></main>`; document.querySelector('#render-error-home').onclick = () => navigate('/'); if (window.lucide) window.lucide.createIcons(); }
    function render() { if (isBooting) return; try { app.innerHTML = ''; const View = views()[state.view] || window.App.Views.NotFound || window.App.Views.Landing; app.appendChild(View()); if (state.isLogged) { window.App.UI?.syncMobileBottomNav?.(state.loggedRole, state.route); } else { document.querySelectorAll('.mobile-bottom-nav').forEach(el => el.remove()); } renderConnectionStatus(); document.querySelectorAll('a[data-route]').forEach(link => { link.href = window.App.Store.hrefFor(link.dataset.route); }); document.querySelectorAll('a[data-tab]').forEach(link => { link.href = window.App.Store.hrefForTab(link.dataset.tabRoute || state.route, link.dataset.tab); }); document.querySelectorAll('a.active').forEach(link => link.setAttribute('aria-current', 'page')); document.title = `SmartCare | ${state.view === 'landing' ? 'Care access, simplified' : state.view === 'notFound' ? 'Page not found' : state.view.charAt(0).toUpperCase() + state.view.slice(1)}`; if (window.lucide) window.lucide.createIcons(); if (window.location.hash) scrollToHash(); else resetScroll(); } catch (error) { console.error('SmartCare view render failed', error); renderFailure(); } }
    document.addEventListener('click', event => { const link = event.target.closest('a'); if (!link) return; if (link.dataset.tab) { event.preventDefault(); navigateTab(link.dataset.tab, link.dataset.tabRoute || state.route); resetScroll(); return; } const rawHref = link.getAttribute('href') || ''; if (rawHref.startsWith('#')) { event.preventDefault(); if (state.view !== 'landing') { navigate(`/${rawHref}`); resetScroll(); return; } const target = document.getElementById(rawHref.slice(1)); if (target) { window.history.replaceState({}, '', `${window.location.pathname}${window.location.search}${rawHref}`); target.scrollIntoView({ behavior: 'smooth', block: 'start' }); } return; } const routeLink = link.matches('[data-route]') ? link : link.closest('a[data-route]'); if (!routeLink) return; event.preventDefault(); navigate(routeLink.dataset.route); resetScroll(); });
    window.addEventListener('popstate', () => syncRoute(false, true));
    window.addEventListener('offline', renderConnectionStatus);
    window.addEventListener('online', () => { renderConnectionStatus(); window.App.UI?.toast?.('Connection restored.', 'success'); });
    renderSplash();
    window.setTimeout(() => { isBooting = false; render(); }, 850);
    subscribe(render);
})();
