(function () {
    const icon = (name, size = 18) => `<i data-lucide="${name}" width="${size}" height="${size}"></i>`;
    const esc = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
    window.App.Views.Analytics = function () {
        const { state, setView, getRevenue, logout } = window.App.Store;
        const container = document.createElement('div');
        container.className = 'flow-shell';
        const bars = [54, 68, 47, 82, 73, 91, 64, 77];
        container.innerHTML = `<div class="flow-topbar"><a class="brand-lockup" data-route="/" href="/"><span class="brand-mark">${icon('heart-pulse', 20)}</span><span><span class="brand-name">SmartCare</span><span class="brand-caption">Analytics workspace</span></span></a><button id="analytics-back" class="back-link">${icon('arrow-left', 16)} Operations</button></div><main class="provider-shell section-dashboard" data-section="analytics-dashboard"><header class="provider-header"><div><div class="eyebrow" style="color:var(--teal)"><span class="eyebrow-dot"></span> Performance analytics</div><h1>See where care slows down.</h1><p>${esc(state.loggedHospital || 'SmartCare network')} · Last 7 days</p></div><div class="provider-date">${icon('calendar-days', 14)} This week<br><strong>Live queue data</strong></div></header><div class="provider-stats"><div class="provider-stat"><span>Visits completed</span><strong>486</strong><small>+8% from last week</small></div><div class="provider-stat"><span>Median wait</span><strong>16m</strong><small>Within target</small></div><div class="provider-stat"><span>Queue exits</span><strong>94%</strong><small>Before 30 minutes</small></div><div class="provider-stat"><span>Queue value</span><strong>₹${getRevenue()}</strong><small>Current active visits</small></div></div><div class="provider-grid"><section class="provider-card" data-section="analytics-volume"><div class="provider-card-heading"><div><h2>Arrivals by hour</h2><p>Use the shape of the day to plan rooms and staff.</p></div></div><div class="chart-bars" role="img" aria-label="Bar chart showing arrivals by hour">${bars.map((height, index) => `<div class="chart-column"><div class="chart-bar" style="height:${height}%" title="${height} visits"></div><small>${8 + index}</small></div>`).join('')}</div></section><section class="provider-card" data-section="analytics-signals"><div class="provider-card-heading"><div><h2>Signals</h2><p>Operational indicators from the live queue.</p></div></div><div class="summary-row"><span>Peak hour</span><strong>13:00</strong></div><div class="summary-row"><span>Most requested</span><strong>General consultation</strong></div><div class="summary-row"><span>Priority queue</span><strong>${state.queue.filter(patient => patient.triage === 'Red').length} open</strong></div><a class="btn-secondary btn-wide btn-icon" data-route="/dashboard/admin" href="/dashboard/admin" style="margin-top:1rem">Back to operations ${icon('arrow-right', 16)}</a></section></div></main>${window.App.UI.footer()}`;
        const workspaceNav = document.createElement('nav');
        workspaceNav.className = 'workspace-tabs';
        workspaceNav.setAttribute('aria-label', 'Analytics workspace navigation');
        workspaceNav.innerHTML = `<a href="/dashboard/admin" data-route="/dashboard/admin">Operations</a><a class="active" href="/dashboard/analytics" data-route="/dashboard/analytics">Analytics</a><a href="#analytics-volume">Volume</a><a href="#analytics-signals">Signals</a><button type="button" id="workspace-logout">Sign out</button>`;
        container.querySelector('main').insertBefore(workspaceNav, container.querySelector('main').firstChild);
        container.querySelector('#workspace-logout').onclick = logout;
        container.querySelector('#analytics-back').onclick = () => setView('staff');
        return container;
    };
})();
