(function () {
    const icon = (name, size = 18) => `<i data-lucide="${name}" width="${size}" height="${size}"></i>`;
    const esc = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
    window.App.Views.Doctor = function () {
        const { state, setView, logout } = window.App.Store;
        const container = document.createElement('div');
        container.className = 'flow-shell workspace-shell';
        const current = state.queue[0] || null;
        const priorityClass = value => value === 'Red' ? 'priority-red' : value === 'Yellow' ? 'priority-yellow' : 'priority-green';
        const rows = state.queue.map((patient, index) => `<tr><td><strong>${index + 1}. ${esc(patient.name)}</strong><small>${esc(patient.age)} years · ${esc(patient.gender || 'Not specified')}</small></td><td>${esc(patient.problem || patient.symptoms || 'General consultation')}</td><td><span class="priority-chip ${priorityClass(patient.triage)}">${esc(patient.triage || 'Green')}</span></td><td>${esc(patient.hospital || state.loggedHospital || 'Care centre')}<small>${esc(patient.city || state.loggedCity || 'Location pending')}</small></td></tr>`).join('');
        container.innerHTML = `<div class="flow-topbar"><a class="brand-lockup" data-route="/" href="/"><span class="brand-mark">${icon('heart-pulse', 20)}</span><span><span class="brand-name">SmartCare</span><span class="brand-caption">Hospital workspace</span></span></a><button id="doctor-back" class="back-link">${icon('arrow-left', 16)} Back to home</button></div><main class="provider-shell section-dashboard" data-section="doctor-dashboard"><header class="provider-header"><div><div class="eyebrow" style="color:var(--teal)"><span class="eyebrow-dot"></span> Hospital workspace</div><h1>Good care needs a clear queue.</h1><p>${esc(state.loggedHospital || 'Your care centre')} · ${esc(state.loggedCity || 'Location not set')}</p></div><div class="provider-date">${new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short' })}<br><strong>${state.queue.length} active visits</strong></div></header><div class="provider-grid"><section class="provider-hero"><div class="eyebrow"><span class="eyebrow-dot"></span> Next in line</div><h2>${current ? esc(current.name) : 'Queue is clear'}</h2><p>${current ? esc(current.problem || current.symptoms || 'General consultation') : 'There are no patients waiting for this care centre right now.'}</p><div class="provider-hero-actions"><button id="complete-patient" class="btn-primary btn-icon" ${current ? '' : 'disabled'}>Complete visit ${icon('check', 16)}</button><button id="refresh-queue" class="btn-secondary btn-icon">Refresh queue ${icon('refresh-cw', 16)}</button></div></section><section class="provider-stats" aria-label="Queue summary"><div class="provider-stat"><span>Waiting now</span><strong>${state.queue.length}</strong><small>Live queue count</small></div><div class="provider-stat"><span>Priority cases</span><strong>${state.queue.filter(p => p.triage === 'Red').length}</strong><small>Needs attention first</small></div><div class="provider-stat"><span>Average wait</span><strong>18m</strong><small>Today at this centre</small></div><div class="provider-stat"><span>Room status</span><strong>Open</strong><small>Consultation room 01</small></div></section></div><section class="provider-card"><div class="provider-card-heading"><div><h2>Patient queue</h2><p>Sort is based on arrival time and triage priority.</p></div><span class="status-eyebrow" style="color:var(--teal)"><i style="background:var(--teal)"></i> Live</span></div>${state.queue.length ? `<div class="queue-table-wrap"><table class="queue-table"><thead><tr><th>Patient</th><th>Reason for visit</th><th>Priority</th><th>Centre</th></tr></thead><tbody>${rows}</tbody></table></div>` : `<div class="provider-empty">${icon('coffee', 30)}<p>Queue clear. New visits will appear here.</p></div>`}</section><div id="doctor-message" class="provider-notice" hidden></div></main>${window.App.UI.footer(true)}`;
        const workspaceNav = document.createElement('nav');
        workspaceNav.className = 'workspace-tabs';
        workspaceNav.setAttribute('aria-label', 'Hospital workspace navigation');
        workspaceNav.innerHTML = `<a class="active" href="/dashboard/doctor" data-route="/dashboard/doctor">${icon('layout-dashboard', 16)}<span>Overview</span></a><a href="/dashboard/queue" data-route="/dashboard/queue">${icon('list-ordered', 16)}<span>Queue</span></a><a href="/dashboard/analytics" data-route="/dashboard/analytics">${icon('bar-chart-3', 16)}<span>Analytics</span></a><a href="/dashboard/doctor/help" data-route="/dashboard/doctor/help">${icon('circle-help', 16)}<span>Help</span></a><button type="button" id="workspace-logout" class="signout-btn">${icon('log-out', 16)}<span>Sign out</span></button>`;
        const workspaceMain = container.querySelector('main');
        const workspaceContent = document.createElement('div');
        workspaceContent.className = 'workspace-content';
        Array.from(workspaceMain.children).forEach(child => workspaceContent.appendChild(child));
        workspaceMain.append(workspaceNav, workspaceContent);
        const quickActions = document.createElement('section');
        quickActions.className = 'dashboard-quick-actions';
        quickActions.setAttribute('aria-label', 'Hospital quick actions');
        quickActions.innerHTML = `<div><span class="eyebrow eyebrow-dark"><span class="eyebrow-dot"></span> Next actions</span><strong>${current ? 'Review the next patient' : 'Keep the queue ready'}</strong><small>${current ? 'Confirm priority and complete the visit when finished.' : 'New reservations will appear here automatically.'}</small></div><button id="quick-call-next" class="btn-primary btn-icon" ${current ? '' : 'disabled'}>${icon('megaphone', 16)} Call next</button><a class="btn-secondary btn-icon" data-route="/dashboard/analytics" href="/dashboard/analytics">Review analytics ${icon('arrow-right', 16)}</a>`;
        workspaceContent.insertBefore(quickActions, workspaceContent.querySelector('.provider-grid'));
        container.querySelector('.provider-card').id = 'queue';
        container.querySelector('#workspace-logout').onclick = logout;
        container.querySelector('#quick-call-next').onclick = () => showMessage(current ? `Calling ${current.name} to the consultation room.` : 'The queue is clear.');
        container.querySelector('#doctor-back').onclick = () => setView('landing');
        container.querySelector('#refresh-queue').onclick = () => window.App.DB.fetchQueue().then(window.App.Store.updateQueue).catch(() => showMessage('Queue refresh is unavailable. Showing the last synced list.'));
        container.querySelector('#complete-patient').onclick = async () => { if (!current) return; const button = container.querySelector('#complete-patient'); button.disabled = true; try { await window.App.DB.removePatient(current.id); } catch (error) { button.disabled = false; showMessage('We could not complete this visit. Check your connection and try again.'); } };
        function showMessage(text) { const message = container.querySelector('#doctor-message'); message.textContent = text; message.hidden = false; }
        return container;
    };
})();
