(function () {
    const icon = (name, size = 18) => `<i data-lucide="${name}" width="${size}" height="${size}"></i>`;
    const esc = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
    const tabLabels = { blood: 'Blood donation', organ: 'Organ donation' };

    window.App.Views.Donation = function () {
        const { state, navigateTab } = window.App.Store;
        const container = document.createElement('div');
        container.className = 'flow-shell donation-shell';
        const activeTab = ['blood', 'organ'].includes(state.activeTab) ? state.activeTab : 'blood';
        const render = () => {
            container.innerHTML = `<div class="flow-topbar donation-topbar"><a class="brand-lockup" data-route="/" href="/"><span class="brand-mark">${icon('heart-pulse', 20)}</span><span><span class="brand-name">SmartCare</span><span class="brand-caption">Community care</span></span></a><nav class="flow-topbar-nav" aria-label="Community navigation"><a data-route="/" href="/">Home</a><a class="active" data-route="/donate" href="/donate">Donation</a><a data-route="/about" href="/about">About</a><a data-route="/login" href="/login">Portal sign in</a></nav><a class="back-link" data-route="/" href="/">${icon('arrow-left', 16)} Back home</a></div><main class="donation-page section-donation" data-section="donation-page"><header class="donation-hero"><div><div class="eyebrow eyebrow-dark"><span class="eyebrow-dot"></span> Community care</div><h1>Small actions can keep care moving.</h1><p>Find blood donation support nearby or record an organ donation interest. This demo does not replace official medical, legal, or registry processes.</p></div><div class="donation-hero-icon" aria-hidden="true">${icon(activeTab === 'blood' ? 'droplets' : 'heart-handshake', 42)}</div></header><nav class="donation-tabs" aria-label="Donation types"><a class="${activeTab === 'blood' ? 'active' : ''}" href="/donate?tab=blood" data-tab="blood" data-tab-route="/donate">${icon('droplets', 17)}<span>Blood donation</span></a><a class="${activeTab === 'organ' ? 'active' : ''}" href="/donate?tab=organ" data-tab="organ" data-tab-route="/donate">${icon('heart-handshake', 17)}<span>Organ donation</span></a></nav>${activeTab === 'blood' ? bloodPanel() : organPanel()}</main>${window.App.UI.footer()}`;
            bind();
            if (window.lucide) window.lucide.createIcons();
        };
        render();
        return container;

        function bloodPanel() {
            return `<section class="donation-grid" data-tab-panel="blood"><div class="donation-card"><div class="eyebrow eyebrow-dark"><span class="eyebrow-dot"></span> Find support</div><h2>Locate a blood donation centre.</h2><p>Choose a blood group and area to see demo support locations.</p><form id="blood-search-form" class="donation-form"><div class="field"><label for="blood-group">Blood group <span>*</span></label><select id="blood-group" required><option value="">Select group</option>${['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map(group => `<option>${group}</option>`).join('')}</select></div><div class="field"><label for="blood-city">City or PIN code <span>*</span></label><input id="blood-city" placeholder="e.g. Hyderabad or 500034" required></div><button class="btn-primary btn-icon" type="submit">Find donation support ${icon('search', 16)}</button></form><div id="blood-results" class="donation-results" aria-live="polite"><p class="status-note">Search for a city to see nearby demo centres.</p></div></div><aside class="donation-card donation-aside"><div class="donation-aside-icon">${icon('shield-check', 21)}</div><h2>Before you donate</h2><ul class="donation-list"><li>Use official screening and eligibility guidance.</li><li>Bring valid identification where required.</li><li>Do not share medical records in this demo.</li></ul><a class="text-link text-link-dark btn-icon" data-route="/about" href="/about">How SmartCare handles demo data ${icon('arrow-right', 15)}</a></aside></section>`;
        }

        function organPanel() {
            return `<section class="donation-grid" data-tab-panel="organ"><div class="donation-card"><div class="eyebrow eyebrow-dark"><span class="eyebrow-dot"></span> Record interest</div><h2>Start an organ donation conversation.</h2><p>Record a non-binding demo interest so a care team can explain official next steps.</p><form id="organ-interest-form" class="donation-form"><div class="field"><label for="organ-name">Your name <span>*</span></label><input id="organ-name" autocomplete="name" placeholder="e.g. Asha Rao" required></div><div class="field"><label for="organ-city">City or state <span>*</span></label><input id="organ-city" placeholder="e.g. Hyderabad" required></div><div class="field"><label for="organ-preference">Interest</label><select id="organ-preference"><option>Learn about donation</option><option>Register interest with a care team</option><option>Support a family conversation</option></select></div><label class="consent-field"><input id="organ-consent" type="checkbox" required><span>I understand this demo is not a legal donor registration or consent form.</span></label><button class="btn-primary btn-icon" type="submit">Save demo interest ${icon('heart-handshake', 16)}</button></form><div id="organ-message" class="donation-message" role="status" aria-live="polite"></div></div><aside class="donation-card donation-aside"><div class="donation-aside-icon">${icon('scale', 21)}</div><h2>Important distinction</h2><p>Legal organ donation registration depends on your country, official registry, family process, and clinical guidance. SmartCare can help start a conversation, not replace that process.</p><a class="text-link text-link-dark btn-icon" href="https://notto.mohfw.gov.in/" target="_blank" rel="noopener noreferrer">Visit India’s official NOTTO site ${icon('external-link', 15)}</a></aside></section>`;
        }

        function bind() {
            container.querySelectorAll('[data-tab]').forEach(link => link.onclick = event => { event.preventDefault(); navigateTab(link.dataset.tab, '/donate'); });
            const bloodForm = container.querySelector('#blood-search-form');
            if (bloodForm) bloodForm.onsubmit = async event => { event.preventDefault(); const group = container.querySelector('#blood-group').value; const city = container.querySelector('#blood-city').value.trim(); const results = container.querySelector('#blood-results'); results.innerHTML = `<p class="status-note">Finding support near ${esc(city)}...</p>`; try { const centres = await window.App.DB.findBloodCentres({ group, city }); results.innerHTML = centres.length ? centres.map(centre => `<article class="donation-result"><div class="donation-result-icon">${icon('droplets', 17)}</div><div><strong>${esc(centre.name)}</strong><p>${esc(centre.area)} · ${esc(centre.hours)}</p><small>${esc(centre.note)}</small></div><button class="text-link" type="button" data-centre="${esc(centre.name)}">View details</button></article>`).join('') : `<div class="provider-empty">${icon('search-x', 26)}<p>No demo centre matched that search.</p></div>`; container.querySelectorAll('[data-centre]').forEach(button => button.onclick = () => window.App.UI.toast(`${button.dataset.centre} accepts blood donation enquiries.`, 'info')); } catch { results.innerHTML = `<div class="inline-error">${icon('triangle-alert', 15)} Donation support is unavailable right now.</div>`; } };
            const organForm = container.querySelector('#organ-interest-form');
            if (organForm) organForm.onsubmit = async event => { event.preventDefault(); const name = container.querySelector('#organ-name').value.trim(); const city = container.querySelector('#organ-city').value.trim(); const preference = container.querySelector('#organ-preference').value; const message = container.querySelector('#organ-message'); if (!name || !city || !container.querySelector('#organ-consent').checked) { message.textContent = 'Add your name, location, and confirm the demo notice before saving.'; message.className = 'donation-message error'; return; } const result = await window.App.DB.submitDonationInterest({ type: 'organ', name, city, preference }); if (!result.success) { message.textContent = result.error || 'We could not save the demo interest.'; message.className = 'donation-message error'; return; } message.textContent = 'Demo interest saved. A future care team flow can connect you with official guidance.'; message.className = 'donation-message success'; window.App.UI.toast('Donation interest saved for this demo.', 'success'); };
        }
    };
})();
