(function () {
    const icon = (name, size = 18) => `<i data-lucide="${name}" width="${size}" height="${size}"></i>`;
    window.App.Views.Info = function () {
        const { state } = window.App.Store;
        const container = document.createElement('div');
        container.className = 'flow-shell';
        const page = state.infoPage || state.view;
        const content = {
            about: { eyebrow: 'About SmartCare', title: 'A clearer path into care.', intro: 'SmartCare is a digital queue access concept for patients and care teams. It helps people choose a nearby centre, share the right context, and arrive with a clearer expectation of the visit.', sections: [['Why it exists', 'Waiting is not the same as care. SmartCare gives patients a simple way to see their options and gives teams a shared view of who needs attention next.'], ['What we are building', 'The demo combines location-aware care discovery, queue visibility, provider workspaces, and accessible service patterns in one small system.'], ['Demo note', 'This workspace is a product prototype. Provider authentication and queue data are connected to the existing service layer for demonstration, not for production clinical use.']] },
            terms: { eyebrow: 'Terms and conditions', title: 'Use SmartCare responsibly.', intro: 'These terms describe the expectations for this demonstration environment. They are intentionally plain so users know what the product is and is not.', sections: [['Demo service', 'SmartCare is provided as a demonstration. Availability, queue estimates, map results, and charges may be incomplete or simulated. Do not use the demo as a substitute for medical advice or emergency response.'], ['Accounts', 'Provider demo accounts are for evaluation. Do not enter real patient records, passwords, or sensitive personal information.'], ['Third-party services', 'Map and location features may use public geocoding and map services. Their availability and terms apply when those services are used.'], ['Changes', 'This prototype may change as the product is tested. The footer shows the last updated date for this environment.']] },
            privacy: { eyebrow: 'Privacy notice', title: 'Keep personal data out of the demo.', intro: 'SmartCare is designed with data minimization in mind. The safest data for this demo is fictional data.', sections: [['What is used', 'The patient flow uses the details required to demonstrate a queue reservation: name, age, location, care centre, and visit reason.'], ['Location', 'Current location is requested only after you choose the location action. It is used to find nearby centres and is not needed to browse the rest of the site.'], ['Your control', 'Use fictional information while testing. To ask about demo data or request a reset, contact support@smartcare.demo.']] }
        }[page] || {};
        container.innerHTML = `<div class="flow-topbar"><a class="brand-lockup" data-route="/" href="/"><span class="brand-mark">${icon('heart-pulse', 20)}</span><span><span class="brand-name">SmartCare</span><span class="brand-caption">Information</span></span></a><a class="back-link" data-route="/" href="/">${icon('arrow-left', 16)} Back to home</a></div><main class="legal-layout section-legal" data-section="${page}"><div class="eyebrow" style="color:var(--teal)"><span class="eyebrow-dot"></span> ${content.eyebrow}</div><h1>${content.title}</h1><p class="legal-intro">${content.intro}</p><div class="legal-sections">${content.sections.map(([heading, text]) => `<section><h2>${heading}</h2><p>${text}</p></section>`).join('')}</div></main>${window.App.UI.footer()}`;
        return container;
    };
})();
