(function () {
    const icon = (name, size = 18) => `<i data-lucide="${name}" width="${size}" height="${size}"></i>`;
    const esc = (value = '') => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
    window.App.Views.Staff = function () {
        const { state, setView, getRevenue, logout } = window.App.Store;
        const container = document.createElement('div');
        container.className = 'flow-shell workspace-shell';
        const rooms = [['Consultation 01', 'Internal medicine', 'In use'], ['Consultation 02', 'General care', 'Available'], ['Triage desk', 'Initial assessment', 'In use'], ['Pharmacy', 'Prescription pickup', 'Available']];
        container.innerHTML = `<div class="flow-topbar"><a class="brand-lockup" data-route="/" href="/"><span class="brand-mark">${icon('heart-pulse', 20)}</span><span><span class="brand-name">SmartCare</span><span class="brand-caption">Operations workspace</span></span></a><button id="staff-back" class="back-link">${icon('arrow-left', 16)} Back to home</button></div><main class="provider-shell section-dashboard" data-section="admin-dashboard"><header class="provider-header"><div><div class="eyebrow" style="color:var(--teal)"><span class="eyebrow-dot"></span> Admin workspace</div><h1>Keep the centre ready.</h1><p>${esc(state.loggedHospital || 'Your care centre')} · ${esc(state.loggedCity || 'Location not set')}</p></div><div class="provider-date">${new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short' })}<br><strong>Operational view</strong></div></header><div class="provider-stats"><div class="provider-stat"><span>Patients today</span><strong>128</strong><small>12% above last month</small></div><div class="provider-stat"><span>Average wait</span><strong>14m</strong><small>2 minutes above target</small></div><div class="provider-stat"><span>Active queue</span><strong>${state.queue.length}</strong><small>Updates in real time</small></div><div class="provider-stat"><span>Projected revenue</span><strong>₹${getRevenue()}</strong><small>Current queue estimate</small></div></div><div class="provider-grid"><section class="provider-card"><div class="provider-card-heading"><div><h2>Room status</h2><p>Make the next handoff visible to the front desk.</p></div><span class="status-eyebrow" style="color:var(--teal)"><i style="background:var(--teal)"></i> Live</span></div><div class="room-grid">${rooms.map(([name, type, status]) => `<div class="room-item"><span>${icon(status === 'Available' ? 'door-open' : 'door-closed', 17)}<strong>${name}</strong><small>${type}</small></span><span class="room-status">${status}</span></div>`).join('')}</div><div class="provider-notice">${icon('triangle-alert', 15)} Triage desk is handling the next priority case. The live queue has ${state.queue.filter(p => p.triage === 'Red').length} red-priority patient(s).</div></section><section class="provider-card"><div class="provider-card-heading"><div><h2>Today at a glance</h2><p>Use these signals to plan the next hour.</p></div></div><div class="summary-row"><span>Peak period</span><strong>10:00–12:00</strong></div><div class="summary-row"><span>Queue health</span><strong>${state.queue.length < 6 ? 'Within target' : 'Needs attention'}</strong></div><div class="summary-row"><span>Facility readiness</span><strong>92%</strong></div><a class="btn-secondary btn-wide btn-icon" data-route="/dashboard/analytics" href="/dashboard/analytics" style="margin-top:1rem">Open analytics <span aria-hidden="true">→</span></a></section></div></main>${window.App.UI.footer()}`;
        const workspaceNav = document.createElement('nav');
        workspaceNav.className = 'workspace-tabs';
        workspaceNav.setAttribute('aria-label', 'Admin workspace navigation');
        workspaceNav.innerHTML = `<a class="active" href="/dashboard/admin" data-route="/dashboard/admin">${icon('layout-dashboard', 16)}<span>Operations</span></a><a href="#rooms">${icon('door-open', 16)}<span>Rooms</span></a><a href="/dashboard/queue" data-route="/dashboard/queue">${icon('list-ordered', 16)}<span>Queue</span></a><a href="/dashboard/analytics" data-route="/dashboard/analytics">${icon('bar-chart-3', 16)}<span>Analytics</span></a><a href="/apply" data-route="/apply">${icon('user-round', 16)}<span>Patient flow</span></a><button type="button" id="workspace-logout">${icon('log-out', 16)}<span>Sign out</span></button>`;
        const workspaceMain = container.querySelector('main');
        const workspaceContent = document.createElement('div');
        workspaceContent.className = 'workspace-content';
        Array.from(workspaceMain.children).forEach(child => workspaceContent.appendChild(child));
        workspaceMain.append(workspaceNav, workspaceContent);
        const quickActions = document.createElement('section');
        quickActions.className = 'dashboard-quick-actions';
        quickActions.setAttribute('aria-label', 'Admin quick actions');
        quickActions.innerHTML = `<div><span class="eyebrow eyebrow-dark"><span class="eyebrow-dot"></span> Next actions</span><strong>Keep the centre moving</strong><small>Review rooms, queue health, and today\'s operating signals.</small></div><a class="btn-primary btn-icon" data-route="/dashboard/analytics" href="/dashboard/analytics">Open analytics ${icon('arrow-right', 16)}</a><a class="btn-secondary btn-icon" data-route="/apply" href="/apply">Preview patient flow ${icon('external-link', 16)}</a>`;
        workspaceContent.insertBefore(quickActions, workspaceContent.querySelector('.provider-stats'));
        container.querySelector('.provider-card').id = 'rooms';
        container.querySelector('#workspace-logout').onclick = logout;
        container.querySelector('#staff-back').onclick = () => setView('landing');
        return container;
    };
})();
